# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import spdk_pb2 as spdk__pb2


class SPDKServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ReplicaCreate = channel.unary_unary(
        '/spdkrpc.SPDKService/ReplicaCreate',
        request_serializer=spdk__pb2.ReplicaCreateRequest.SerializeToString,
        response_deserializer=spdk__pb2.Replica.FromString,
        )
    self.ReplicaDelete = channel.unary_unary(
        '/spdkrpc.SPDKService/ReplicaDelete',
        request_serializer=spdk__pb2.ReplicaDeleteRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ReplicaGet = channel.unary_unary(
        '/spdkrpc.SPDKService/ReplicaGet',
        request_serializer=spdk__pb2.ReplicaGetRequest.SerializeToString,
        response_deserializer=spdk__pb2.Replica.FromString,
        )
    self.ReplicaSnapshotCreate = channel.unary_unary(
        '/spdkrpc.SPDKService/ReplicaSnapshotCreate',
        request_serializer=spdk__pb2.SnapshotRequest.SerializeToString,
        response_deserializer=spdk__pb2.Replica.FromString,
        )
    self.ReplicaSnapshotDelete = channel.unary_unary(
        '/spdkrpc.SPDKService/ReplicaSnapshotDelete',
        request_serializer=spdk__pb2.SnapshotRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ReplicaList = channel.unary_unary(
        '/spdkrpc.SPDKService/ReplicaList',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=spdk__pb2.ReplicaListResponse.FromString,
        )
    self.ReplicaWatch = channel.unary_stream(
        '/spdkrpc.SPDKService/ReplicaWatch',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.EngineCreate = channel.unary_unary(
        '/spdkrpc.SPDKService/EngineCreate',
        request_serializer=spdk__pb2.EngineCreateRequest.SerializeToString,
        response_deserializer=spdk__pb2.Engine.FromString,
        )
    self.EngineDelete = channel.unary_unary(
        '/spdkrpc.SPDKService/EngineDelete',
        request_serializer=spdk__pb2.EngineDeleteRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.EngineGet = channel.unary_unary(
        '/spdkrpc.SPDKService/EngineGet',
        request_serializer=spdk__pb2.EngineGetRequest.SerializeToString,
        response_deserializer=spdk__pb2.Engine.FromString,
        )
    self.EngineSnapshotCreate = channel.unary_unary(
        '/spdkrpc.SPDKService/EngineSnapshotCreate',
        request_serializer=spdk__pb2.SnapshotRequest.SerializeToString,
        response_deserializer=spdk__pb2.Engine.FromString,
        )
    self.EngineSnapshotDelete = channel.unary_unary(
        '/spdkrpc.SPDKService/EngineSnapshotDelete',
        request_serializer=spdk__pb2.SnapshotRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.EngineList = channel.unary_unary(
        '/spdkrpc.SPDKService/EngineList',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=spdk__pb2.EngineListResponse.FromString,
        )
    self.EngineWatch = channel.unary_stream(
        '/spdkrpc.SPDKService/EngineWatch',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.EngineReplicaDelete = channel.unary_unary(
        '/spdkrpc.SPDKService/EngineReplicaDelete',
        request_serializer=spdk__pb2.EngineReplicaDeleteRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.DiskCreate = channel.unary_unary(
        '/spdkrpc.SPDKService/DiskCreate',
        request_serializer=spdk__pb2.DiskCreateRequest.SerializeToString,
        response_deserializer=spdk__pb2.Disk.FromString,
        )
    self.DiskDelete = channel.unary_unary(
        '/spdkrpc.SPDKService/DiskDelete',
        request_serializer=spdk__pb2.DiskDeleteRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.DiskGet = channel.unary_unary(
        '/spdkrpc.SPDKService/DiskGet',
        request_serializer=spdk__pb2.DiskGetRequest.SerializeToString,
        response_deserializer=spdk__pb2.Disk.FromString,
        )
    self.VersionDetailGet = channel.unary_unary(
        '/spdkrpc.SPDKService/VersionDetailGet',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=spdk__pb2.VersionDetailGetReply.FromString,
        )


class SPDKServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ReplicaCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplicaDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplicaGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplicaSnapshotCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplicaSnapshotDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplicaList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplicaWatch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EngineCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EngineDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EngineGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EngineSnapshotCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EngineSnapshotDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EngineList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EngineWatch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EngineReplicaDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DiskCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DiskDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DiskGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VersionDetailGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SPDKServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ReplicaCreate': grpc.unary_unary_rpc_method_handler(
          servicer.ReplicaCreate,
          request_deserializer=spdk__pb2.ReplicaCreateRequest.FromString,
          response_serializer=spdk__pb2.Replica.SerializeToString,
      ),
      'ReplicaDelete': grpc.unary_unary_rpc_method_handler(
          servicer.ReplicaDelete,
          request_deserializer=spdk__pb2.ReplicaDeleteRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ReplicaGet': grpc.unary_unary_rpc_method_handler(
          servicer.ReplicaGet,
          request_deserializer=spdk__pb2.ReplicaGetRequest.FromString,
          response_serializer=spdk__pb2.Replica.SerializeToString,
      ),
      'ReplicaSnapshotCreate': grpc.unary_unary_rpc_method_handler(
          servicer.ReplicaSnapshotCreate,
          request_deserializer=spdk__pb2.SnapshotRequest.FromString,
          response_serializer=spdk__pb2.Replica.SerializeToString,
      ),
      'ReplicaSnapshotDelete': grpc.unary_unary_rpc_method_handler(
          servicer.ReplicaSnapshotDelete,
          request_deserializer=spdk__pb2.SnapshotRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ReplicaList': grpc.unary_unary_rpc_method_handler(
          servicer.ReplicaList,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=spdk__pb2.ReplicaListResponse.SerializeToString,
      ),
      'ReplicaWatch': grpc.unary_stream_rpc_method_handler(
          servicer.ReplicaWatch,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'EngineCreate': grpc.unary_unary_rpc_method_handler(
          servicer.EngineCreate,
          request_deserializer=spdk__pb2.EngineCreateRequest.FromString,
          response_serializer=spdk__pb2.Engine.SerializeToString,
      ),
      'EngineDelete': grpc.unary_unary_rpc_method_handler(
          servicer.EngineDelete,
          request_deserializer=spdk__pb2.EngineDeleteRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'EngineGet': grpc.unary_unary_rpc_method_handler(
          servicer.EngineGet,
          request_deserializer=spdk__pb2.EngineGetRequest.FromString,
          response_serializer=spdk__pb2.Engine.SerializeToString,
      ),
      'EngineSnapshotCreate': grpc.unary_unary_rpc_method_handler(
          servicer.EngineSnapshotCreate,
          request_deserializer=spdk__pb2.SnapshotRequest.FromString,
          response_serializer=spdk__pb2.Engine.SerializeToString,
      ),
      'EngineSnapshotDelete': grpc.unary_unary_rpc_method_handler(
          servicer.EngineSnapshotDelete,
          request_deserializer=spdk__pb2.SnapshotRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'EngineList': grpc.unary_unary_rpc_method_handler(
          servicer.EngineList,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=spdk__pb2.EngineListResponse.SerializeToString,
      ),
      'EngineWatch': grpc.unary_stream_rpc_method_handler(
          servicer.EngineWatch,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'EngineReplicaDelete': grpc.unary_unary_rpc_method_handler(
          servicer.EngineReplicaDelete,
          request_deserializer=spdk__pb2.EngineReplicaDeleteRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'DiskCreate': grpc.unary_unary_rpc_method_handler(
          servicer.DiskCreate,
          request_deserializer=spdk__pb2.DiskCreateRequest.FromString,
          response_serializer=spdk__pb2.Disk.SerializeToString,
      ),
      'DiskDelete': grpc.unary_unary_rpc_method_handler(
          servicer.DiskDelete,
          request_deserializer=spdk__pb2.DiskDeleteRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'DiskGet': grpc.unary_unary_rpc_method_handler(
          servicer.DiskGet,
          request_deserializer=spdk__pb2.DiskGetRequest.FromString,
          response_serializer=spdk__pb2.Disk.SerializeToString,
      ),
      'VersionDetailGet': grpc.unary_unary_rpc_method_handler(
          servicer.VersionDetailGet,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=spdk__pb2.VersionDetailGetReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'spdkrpc.SPDKService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
