---
kind: pipeline
name: default-amd64

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - main

steps:
- name: fetch
  image: ubuntu:18.04
  commands:
  - apt-get update
  - apt-get install -y git
  - git fetch --tags

- name: build
  pull: default
  image: rancher/dapper:v0.5.3
  commands:
  - dapper ci
  volumes:
  - name: socket
    path: /var/run/docker.sock

- name: codecov
  image: robertstettner/drone-codecov
  settings:
    token:
      from_secret: CODECOV_TOKEN
    debug: true

volumes:
- name: socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: default-arm64

platform:
  os: linux
  arch: arm64

trigger:
  branch:
  - main

steps:
- name: fetch
  image: ubuntu:18.04
  commands:
  - apt-get update
  - apt-get install -y git
  - git fetch --tags

- name: build
  pull: default
  image: rancher/dapper:v0.5.3
  commands:
  - dapper ci
  volumes:
  - name: socket
    path: /var/run/docker.sock

volumes:
- name: socket
  host:
    path: /var/run/docker.sock

