import os

INSTANCE_MANAGER_PROCESS_MANAGER = "localhost:8500"
INSTANCE_MANAGER_DISK = "localhost:8502"
INSTANCE_MANAGER_INSTANCE = "localhost:8503"
INSTANCE_MANAGER_SPDK = "localhost:8504"

DISK_TYPE = "block"
DISK_NAME = "test-disk"
DISK_PATH = "/dev/im-disk"
DISK_BLOCK_SIZE = 4096

POD_IP = "127.0.0.1"
