#!/bin/bash
set -e

LOCK_FILE="/tmp/longhorn-spdk.lock"
MAX_WAIT=36000  # seconds

# Try to acquire exclusive lock on $LOCK_FILE using file descriptor 200
# If the lock is held by another process, wait and retry
# Try to acquire exclusive lock on $LOCK_FILE using file descriptor 200
# Wait up to $MAX_WAIT seconds
exec 200>"$LOCK_FILE"
if ! flock -w "$MAX_WAIT" 200; then
  echo "Failed to acquire lock on $LOCK_FILE after $MAX_WAIT seconds. Exiting."
  exit 1
fi

cd "$(dirname $0)"/..

echo Running unit tests

# in case there is error before calling go test ...
touch coverage.out

# Check if hugepages are configured
hugepages="$(grep HugePages_Total < /proc/meminfo | awk '{print $2}')"
if [ -z "$hugepages" ] || [ 1 -gt $hugepages ]
then
  echo No hugepages configured on the host for the test
  exit 1
fi

mount --rbind /host/dev /dev
mount --rbind /host/sys /sys

echo "Checking /dev/hugepages"
if [ ! -d /dev/hugepages ]; then
  echo "Creating /dev/hugepages"
  mkdir -p /dev/hugepages
  mount -t hugetlbfs nodev /dev/hugepages
fi

trap "umount /dev && umount /sys && umount /dev/hugepages" EXIT

# Do cleanup first
losetup -D
trap "losetup -D" EXIT

PACKAGES="$(find . -name '*.go' -print0 | xargs -0 -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|.trash-cache|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"

trap "rm -f /tmp/test-disk" EXIT

go test -v -p 1 -race -cover ${PACKAGES} -coverprofile=coverage.out -timeout 180m
