name: build
on:
  push:
    branches:
    - master
    - v*
    tags:
    - v*
  pull_request:
  workflow_dispatch:
jobs:
  build-amd64:
    name: Build AMD64 binaries
    runs-on: longhorn-infra-oracle-amd64-spdk-runners
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Install make curl git kmod
      run: |
        sudo apt update
        sudo apt-get -y install make curl git kmod
    # Build binaries
    - name: Run ci
      run: make ci

    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
      with:
        files: ./coverage.out
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}

  build-arm64:
    name: Build ARM64 binaries
    runs-on: longhorn-infra-oracle-arm64-spdk-runners
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Install make curl git kmod
      run: |
        sudo apt update
        sudo apt-get -y install make curl git kmod
    # Build binaries
    - name: Run ci
      run: sudo make ci

    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
      with:
        files: ./coverage.out
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
