name: build
on:
  push:
    branches:
    - master
    - v*
    tags:
    - v*
  pull_request:
  workflow_dispatch:
jobs:
  build-amd64:
    name: Build AMD64 binaries
    runs-on: cncf-ubuntu-16-64-x86
    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Install make curl git kmod
      run: |
        sudo apt update
        sudo apt-get -y install make curl git kmod

    - name: Set up hugepages
      run: |
        sudo sh -c "echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages"
        grep Huge /proc/meminfo

    - name: Load kernel modules
      run: sudo modprobe nvme-tcp vfio_pci uio_pci_generic ublk_drv

    # Build binaries
    - name: Run ci
      run: sudo make ci

    - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
      with:
        files: ./coverage.out
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}

  build-arm64:
    name: Build ARM64 binaries
    runs-on: oracle-vm-16cpu-64gb-arm64
    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Install make curl git kmod
      run: |
        sudo apt update
        sudo apt-get -y install make curl git kmod

    - name: Set up hugepages
      run: |
        sudo sh -c "echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages"
        grep Huge /proc/meminfo

    - name: Load kernel modules
      run: sudo modprobe nvme-tcp vfio_pci uio_pci_generic ublk_drv

    # Build binaries
    - name: Run ci
      run: sudo make ci

    - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
      with:
        files: ./coverage.out
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
